#!/usr/bin/env sh

browsers=(chrome google-chrome chromium chromium-browser)

for browser in ${browsers[*]}
do
  abspath=$(which $browser 2> /dev/null)
  if [[ ! -z "$abspath" ]]
  then
    exec $abspath "${@}"
  fi
done

>&2 echo "No chrome or chromium executable found in PATH"

exit 1
